var equation = require('./modules/equation.js');
var fs = require('fs');
var file = "input.json";
var packageJSON = JSON.parse(fs.readFileSync(file));
var a = packageJSON.a;
var b = packageJSON.b;
var c = packageJSON.c;
var whatever = equation.matematika(a,b,c);
console.log(JSON.stringify(whatever , null, 2));
